version: 2
jobs:
  test_jdk8_with_coverage:
    working_directory: ~/flo
    docker:
      - image: maven:3.6.0-jdk-8
    steps:
      - checkout
      - restore_cache:
          key: v1-deps-{{ checksum "pom.xml" }}
      - run:
          environment:
            # Maven heap size
            MAVEN_OPTS: -Xmx1024m -Xms1024m
          command: mvn -B dependency:go-offline compile test-compile
      - save_cache:
          key: v1-deps-{{ checksum "pom.xml" }}
          paths:
            - ~/.m2
      - run:
          environment:
            # Maven heap size
            MAVEN_OPTS: -Xmx1024m -Xms1024m
          command: mvn -B verify scala:doc-jar -Pcoverage
      - run: bash <(curl -s https://codecov.io/bash)

  test_jdk11:
    working_directory: ~/styx
    docker:
      - image: maven:3.6.0-jdk-11-slim
    steps:
      - checkout
      - restore_cache:
          key: v1-deps-jdk11-{{ checksum "pom.xml" }}
      - run:
          environment:
            # Maven heap size
            MAVEN_OPTS: -Xmx1024m -Xms1024m
          command: mvn -B dependency:go-offline compile test-compile
      - save_cache:
          key: v1-deps-jdk11-{{ checksum "pom.xml" }}
          paths:
            - ~/.m2
      - run: mvn -B verify scala:doc-jar

workflows:
  version: 2
  build:
    jobs:
      - test_jdk8_with_coverage:
          filters:
            branches:
              ignore: gh-pages
      - test_jdk11:
          filters:
            branches:
              ignore: gh-pages
